language: c
compiler:
 - gcc
 - clang
env:
 - BUILD_TYPE=Debug
 - BUILD_TYPE=Release
branches:
  only:
    - master
    - /wildmidi-.*$/
before_install:
 - pwd
 - git submodule update --init --recursive
 - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgtest-dev google-mock 
 - sudo apt-get install -qq libasound2-dev libopenal-dev osspd
 - sudo mkdir /usr/src/gtest/build
 - cd /usr/src/gtest/build
 - sudo cmake .. -DBUILD_SHARED_LIBS=1
 - sudo make -j4
 - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
 - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
before_script:
 - cd -
 - mkdir debug
 - cd debug
 - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
script:
 - make -j2

#after_script:
# - ./runtests
notifications:
  recipients:
    - psi29a+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
  irc:    
    channels:
      - "chat.freenode.net#wildmidi"
    on_success: always
    on_failure: always    
