language: c
compiler:
 - gcc
# - clang
branches:
  only:
    - master
before_install:
 - pwd
 - git submodule update --init --recursive
 - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
 - sudo apt-get update -qq
 - sudo apt-get install -qq libgtest-dev google-mock 
 - sudo apt-get install -qq libasound2-dev
 - sudo mkdir /usr/src/gtest/build
 - cd /usr/src/gtest/build
 - sudo cmake .. -DBUILD_SHARED_LIBS=1
 - sudo make -j4
 - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/lib/libgtest.so
 - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/lib/libgtest_main.so
before_script:
 - cd -
 - mkdir build
 - cd build
 - cmake ..
script:
 - make -j4
#after_script:
# - ./runtests
notifications:
  recipients:
    - psi29a+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
